name: idealschool
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.19.0
  path_provider: ^2.1.1
  uuid: ^4.4.0
  syncfusion_flutter_charts: ^25.1.40
  fluttertoast: ^8.2.8
  flutter_social_button: ^1.1.4+1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.5
  provider: ^6.1.2
  get: ^4.6.6
  flutter_native_splash: ^2.4.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  firebase_storage: ^11.7.5
  gif: ^2.3.0
  fl_chart: ^0.68.0
  firebase_messaging: ^14.9.4
  google_fonts: ^6.2.1
  table_calendar: ^3.1.2
  http: ^1.2.1
  flip_card: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ic_launcher.png
    - assets/images/ono.gif
    - assets/images/ono1.gif
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/7.png
    - assets/images/8.png
    - assets/images/9.png
    - assets/images/10.png
    - assets/images/11.png
    - assets/images/12.png
    - assets/images/13.png
    - assets/images/14.png
    - assets/images/15.png
    - assets/images/16.png
    - assets/images/17.png
    - assets/images/18.png
    - assets/images/cover.png
    - assets/images/cover-1.png
    - assets/images/cover-2.png
    - assets/images/cover-3.png
    - assets/images/kg.png
    - assets/images/kg-1.png
    - assets/images/kg-2.png
    - assets/images/kg-3.png
    - assets/images/kg-4.png
    - assets/images/a.png
    - assets/images/b.png
    - assets/images/c.png
    - assets/images/e.png
    - assets/images/w.png
    - assets/images/1a.png
    - assets/images/m.png
    - assets/images/m1.png
    - assets/images/m12.png
    - assets/images/x.png
    - assets/images/bookmar.png
    - assets/images/near.png
    - assets/images/spl.png
    - assets/images/nat.png
    - assets/images/playstore.png
    - assets/images/demo.gif

flutter_native_splash:
  color: "#301934"
  image: assets/images/nat.png
  android: true
  ios: true
  web: true
