// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEHJ1m-E4mdEUC-sEqxwHvbHMCK0AkCLE',
    appId: '1:241449031019:web:1bbd00ed7852b83d5fa82e',
    messagingSenderId: '241449031019',
    projectId: 'idealschool-3beeb',
    authDomain: 'idealschool-3beeb.firebaseapp.com',
    databaseURL: 'https://idealschool-3beeb-default-rtdb.firebaseio.com',
    storageBucket: 'idealschool-3beeb.appspot.com',
    measurementId: 'G-6S1Q74B30Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRtWNRfTJiue6y38oL8LYbACVy31AZpRY',
    appId: '1:241449031019:android:c7ee952405e7ed485fa82e',
    messagingSenderId: '241449031019',
    projectId: 'idealschool-3beeb',
    databaseURL: 'https://idealschool-3beeb-default-rtdb.firebaseio.com',
    storageBucket: 'idealschool-3beeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsm7LBJo88oCL7dFFW_q4mwmoHBlfYqwU',
    appId: '1:241449031019:ios:7852b315b2d4e0595fa82e',
    messagingSenderId: '241449031019',
    projectId: 'idealschool-3beeb',
    databaseURL: 'https://idealschool-3beeb-default-rtdb.firebaseio.com',
    storageBucket: 'idealschool-3beeb.appspot.com',
    androidClientId: '241449031019-ki4fkp3epep2582rp5q2clr1ufn3g1js.apps.googleusercontent.com',
    iosClientId: '241449031019-8il5qutv3gkqumrjfseee77vv6lbr66k.apps.googleusercontent.com',
    iosBundleId: 'com.example.idealSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsm7LBJo88oCL7dFFW_q4mwmoHBlfYqwU',
    appId: '1:241449031019:ios:7852b315b2d4e0595fa82e',
    messagingSenderId: '241449031019',
    projectId: 'idealschool-3beeb',
    databaseURL: 'https://idealschool-3beeb-default-rtdb.firebaseio.com',
    storageBucket: 'idealschool-3beeb.appspot.com',
    androidClientId: '241449031019-ki4fkp3epep2582rp5q2clr1ufn3g1js.apps.googleusercontent.com',
    iosClientId: '241449031019-8il5qutv3gkqumrjfseee77vv6lbr66k.apps.googleusercontent.com',
    iosBundleId: 'com.example.idealSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEHJ1m-E4mdEUC-sEqxwHvbHMCK0AkCLE',
    appId: '1:241449031019:web:90a48fe0c0d2d62c5fa82e',
    messagingSenderId: '241449031019',
    projectId: 'idealschool-3beeb',
    authDomain: 'idealschool-3beeb.firebaseapp.com',
    databaseURL: 'https://idealschool-3beeb-default-rtdb.firebaseio.com',
    storageBucket: 'idealschool-3beeb.appspot.com',
    measurementId: 'G-3B8JNMXZ5Z',
  );
}
