// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRtWNRfTJiue6y38oL8LYbACVy31AZpRY',
    appId: '1:241449031019:android:1c5e103eb1100cb45fa82e',
    messagingSenderId: '241449031019',
    projectId: 'idealschool-3beeb',
    databaseURL: 'https://idealschool-3beeb-default-rtdb.firebaseio.com',
    storageBucket: 'idealschool-3beeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsm7LBJo88oCL7dFFW_q4mwmoHBlfYqwU',
    appId: '1:241449031019:ios:b1209187d6d8f7555fa82e',
    messagingSenderId: '241449031019',
    projectId: 'idealschool-3beeb',
    databaseURL: 'https://idealschool-3beeb-default-rtdb.firebaseio.com',
    storageBucket: 'idealschool-3beeb.appspot.com',
    iosBundleId: 'com.example.idealschool',
  );
}
